CREATE OR ALTER PROCEDURE SP_SAVE_TH_GUI_USER_AUTH
(
	 @CMP_CD		VARCHAR(20)
	,@MENU_CD		VARCHAR(100)
	,@USER_ID		VARCHAR(20)	
	,@USER_AUTH		INT
	,@USE_YN		CHAR(1)
	,@REG_ID		VARCHAR(20)
)
AS
BEGIN

	IF EXISTS (SELECT 1 FROM TH_GUI_USER_AUTH WHERE CMP_CD = @CMP_CD AND MENU_CD = @MENU_CD AND USER_ID = @USER_ID)
	BEGIN
　		UPDATE TH_GUI_USER_AUTH
		SET
			 USER_AUTH		= @USER_AUTH
			,USE_YN			= @USE_YN	
			,MDF_ID			= @REG_ID
			,MDF_DM			= CURRENT_TIMESTAMP
		WHERE   CMP_CD = @CMP_CD
			AND MENU_CD = @MENU_CD
			AND USER_ID = @USER_ID
	END
	ELSE
	BEGIN
		INSERT INTO TH_GUI_USER_AUTH (
			 CMP_CD  
			,MENU_CD             
			,USER_ID               
			,USER_AUTH
			,USE_YN           
			,REG_ID
			,REG_DM
		) 
		VALUES (
			 @CMP_CD
			,@MENU_CD
			,@USER_ID               
			,@USER_AUTH
			,@USE_YN	
			,@REG_ID
			,CURRENT_TIMESTAMP
		)
	END

END;